"""added columns 'detail' and 'deliver' in class Order

Revision ID: 3f13012607f4
Revises: 44cf8fbbd696
Create Date: 2019-04-18 20:45:14.522674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f13012607f4'
down_revision = '44cf8fbbd696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('deliver', sa.Text(), nullable=False))
    op.add_column('order', sa.Column('detail', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'detail')
    op.drop_column('order', 'deliver')
    # ### end Alembic commands ###
