"""new columns added

Revision ID: 44cf8fbbd696
Revises: c57dd21cf356
Create Date: 2019-04-13 13:40:59.178724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cf8fbbd696'
down_revision = 'c57dd21cf356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('image', sa.String(), nullable=True))
    op.add_column('book', sa.Column('pages', sa.String(), nullable=True))
    op.add_column('book', sa.Column('printed_in', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'printed_in')
    op.drop_column('book', 'pages')
    op.drop_column('author', 'image')
    # ### end Alembic commands ###
