"""Comments model

Revision ID: 5768de65b1c4
Revises: 3f13012607f4
Create Date: 2019-04-21 16:10:47.522108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5768de65b1c4'
down_revision = '3f13012607f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_feedback', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_feedback', 'created')
    # ### end Alembic commands ###
